plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = 'gretl-doclet'
}

dependencies {
    testImplementation gradleApi()
    testImplementation project(':gretl-core')
    testImplementation project(':gretl-geotools')
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testImplementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
}

tasks.register('generateLspMetadata') {
    group = 'documentation'
    description = 'Generates GRETL LSP metadata JSON file.'
    dependsOn rootProject.tasks.named('generateLspMetadata')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
