name: Website

on:
  push:
    branches: [main, master]
    paths:
      - 'website/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dummy
        run: echo "Website workflow placeholder"
